const DestinyNumberBenefits = {
    "1": "The number One person is a born leader. You will find yourself in a leadership role at some point in your life and it is who you are, independent, original and with a lot of initiative. Your life is destined to be interesting, with all your experiences there to help you develop your your steely determination, willpower and drive to succeed in your life. You need not be too aggressive or overbearing, just use your immense strengths to help you get what you want in life.",
    "2": "The number Two person is a born diplomat. You are a naturally diplomatic, level-headed and calm person. You have excellent powers of persuasion which you use well to calm any difficult person or situation. You may not always want to be the peace-maker, but you will always be called upon to be this person because everyone respects your skills in this area. You are a very loving and caring person, but you can become a little too overly concerned for your family and loved ones, with your over-protective nature making them feel hemmed in.",
    "3": "The number Three person is a total optimist. You are such a cheerful, bright, enthusiastic person who is very creative on many levels. You make a great companion for your partner or friends. You do well in business because you have a need to succeed in everything you take on. If you ever fail in anything, it hits you hard but you don't like to show your disappointments to anyone, so you just hide your pain behind your natural wit and humor so non-one ever knows.",
    "4": "The number Four person is the ultimate manager who has great organizational skills. You are very efficient, methodical and systematic in the way you approach everything in life. You are the one who makes lists for everything you do - daily acclivities, work, shopping, everything! You are the perfect employee as you have a great way of being able to improve on current systems, so employers would do well to have you on their staff.",
    "5": "The number Five person is a total communicator. You need variety and change in your life, otherwise you quickly become bored. You tend not to keep most of your friends for life, probably because you outgrow most of the people you know at any stage in your life. You have an innate restlessness which causes you to seek new experiences and this is which makes you change your path in life many times, because the one you are on now may soon bore you. Your attention span is very low, so you need constant excitement and variety.",
    "6": "The number Six person is a nurturer. Your mission in life is to help those who are weak, unhappy and ailing in any way. You are a perfectionist, who is always striving to achieve the best possible for yourself. This makes you a hard task master, with high expectations for yourself and for others. Learn to release this need for perfection and life will flow even better. Surprisingly you actually do well in your own business, because you can channel all your care and tenderness to nurture it to grow and flourish. You also employ the best people to help you achieve success.",
    "7": "The number Seven person is the educator and mystic. You are the one who loves to study everything, to research and work out fact from fantasy. You have a particular fascination with the hidden and mysterious, such as the occult and may even have some latent (or developed) psychic abilities. You make a wonderful partner, who is loving and caring, but you need to have freedom to follow your own pursuits. You would not do well with an overly domineering partner.",
    "8": "The number Eight person is the successful business person. You thrive on responsibility and need to be in a position of authority and power. You need recognition from others of your many talents. You put in the hard work to achieve your goals, which means you tend to be more successful than the other Destiny Numbers, as you put in such a great effort to reach your goals.",
    "9": "The number Nine person is the philanthropic, charitable and beautiful one. You have a fine appreciation for all things artistic and try to live your life in a way that beautifies your world in some way, no matter what you do. You have a great power to awaken people to the beauty that is inside their hearts and to help them achieve their goals.",
    "11": "The number Eleven person is the performer. You are often associated with television, films or journalism - any career which puts you in front of a camera and which means you are in the public eye. You are a great communicator and so this means you also write very well. Your communication skills are useful when you impart your skills and knowledge onto other people. You have a knack of making friends who are influential and powerful and can help you in your life in some way. You have a lot of people who look up to you, as you go from success to success, which means you would be the perfect leader of any community, as people will listen to what you say and follow your lead.",
    "22": "The number Twenty-two person is the one with magnetism and charisma. Even if you are not particularly beautiful, you have such a magnetism that draws other people to you. Your charming demeanor means you find yourself in the center of attention a lot, which you use to advance yourself in whatever way you can."
}

module.exports = DestinyNumberBenefits

