const LifePathBenefits = {
    "1": "Number 1 people are the leaders, the ones who are in charge. You have a strong determination and a purpose in life which you move toward each day. You are very ambitious and want to succeed in life.You have a lot of energy and power, as well as a strong belief in yourself. You are generally positive and enthusiastic, with a lot of independence.",
    "2": "Number 2 people are well-balanced, sociable, cheerful, and have a sensitivity and and inner genteelness. Your home, loved ones and family are very important to you. You need to be in harmonious surroundings to feel happiest. Your feelings are very sensitive and you can become easily hurt by others, which can lead to episodes of depression.",
    "3": "Number 3 people are the adaptable, versatile and charming ones. You are very restless and need to be moving forward and changing direction every few years in your life. You have a variety of interests which you may pursue at some stage in your life. You are always good company in social situations, you love to socialize and are such a charming, witty and interesting companion. Your outward sunny and vibrant nature belies the worries and insecurities you have inside, which you don't really show and so most people don't get to see this side of you.",
    "4": "Number 4 people are very hardworking, sensible, practical and need to feel stable to succeed in life. Once you have decided on a path in life, you tend to stick to it until you achieve it. You are very loyal and dedicated to your close friends, lovers and family. You always learn from your mistakes and order and logic appeal greatly to you. You are the best person in an emergency as you know exactly what to do and will go about it rational and calmly while others panic.",
    "5": "Number 5 people are very creative and artistic. You have a great deal of energy and thirst for life and all you can experience. You are changeable and dislike routine of any sort as you need variety and excitement. You make friends very easily and often lend a sympathetic ear to your many friends - you have the most friends of all the Life Numbers.",
    "6": "6 is the number of harmony and balance (as it is closely linked with Libra). Number 6 people are great at balancing all areas of your life - friends, family, work and your partner better than the other Life Numbers. You have an interest in health and especially nutrition and will always try your best to feed your family well although you may not take care of yourself as well. You are very attractive and magnetic to other people. You usually succeed in business, so your finances are healthy which allows you to indulge in your favorite luxury items.",
    "7": "Number 7 people are the spiritual and intuitive ones. You are more often than not gifted with a psychic ability, which you should develop. You are a great mediator, you know exactly how to achieve peace between two warring parties. You are very sensitive, introspective and have a developed spirituality, irrespective of whether you follow a specific religion or not. You often have very vivid dreams which you almost always remember. You are an idealist and a thinker.",
    "8": "Number 8 people need to succeed in all pursuits. You especially need financial security in order to feel happy with your life. You are ambitious, self-sufficient and career-minded. You don't give up on your goals and you often reach them even when there are huge hurdles along the way. You are stubborn, intense, persistent and a deep thinker, with great powers of concentration. You are very well organized and practical, so this goes a long way to helping you achieve your many goals in life.",
    "9": "Number 9 people are very creative and have a high awareness of your own spirituality. You tend to gravitate towards careers where you can help mankind, especially through charitable work and even if you do not work in this area, you will be the first to donate to your charities and spend more time thinking about ways you can improve the lot of mankind. You are very honest, courteous and friendly, although you can be quite impressionable by people you highly respect. You are very passionate and appear a lot older than you actually are. You are a natural philosopher who values knowledge for its own sake, you have a need to know about everything.",
    "11": "The Number 11 is the first Master Number, which means it is a number of strength and power. This number should never be reduced to a single digit as it is a special number. As a Number 11 person, you are usually successful in any goal you want to achieve, rarely failing in anything, you just keep on moving forward and onwards. You have a lot of energy, drive and will power, especially when it comes to your ambitions. You will take calculated risks that almost always give you positive results (much to the chagrin of some).",
    "22": "The Number 22 is another Master Number which is seen as the number of perfection. This number should never be reduced to a single digit as it is a special number. As a Number 22 person, you should have a pretty good life, not without any disappointment or loss, but generally less than others. You appear to have success in all your endeavors without really trying very hard (it isn't the case, but that is how you come across to others)."
}

module.exports = LifePathBenefits;